title: Notes
description: Quick brain dumps of nerd stuff
url: https://jeroen66124.github.io
theme: just-the-docs
color_scheme: dark
nav_enabled: false
search_enabled: true
aux_links_new_tab: true

aux_links:
  ITQ: https://itq.eu/author/jeroenk/
  LinkedIn: https://www.linkedin.com/in/jkou/
  Credly: https://www.credly.com/users/jkou/
